# Site settings
title: Chad's Blog
email: chad.chandrapaul@gmail.com  # Update this with your actual email
description: Exploring emerging technologies, personal development, and project learnings
url: "https://curlysoldier.github.io"
baseurl: "/blog"

# Theme selection - choose one of these:
# theme: minima                    # Default Jekyll theme (uncomment to use)
remote_theme: pages-themes/minimal     # Clean, simple theme (recommended for learning)
# remote_theme: pages-themes/cayman     # Modern with gradient header
# remote_theme: pages-themes/architect  # Professional, header-focused
# remote_theme: pages-themes/leap-day   # Clean, professional layout

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Chad Chandrapaul"
