# Site settings
title: Chad's Blog
email: chad.chandrapaul@gmail.com  # Update this with your actual email
description: Exploring emerging technologies, personal development, and project learnings
url: "https://curlysoldier.github.io"
baseurl: "/blog"

# Theme selection - choose one of these:
theme: minima

# Build settings
# markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Simple permalink structure
permalink: /:year/:title/

# Suppress Sass deprecation warnings for cleaner builds
sass:
  quiet_deps: true
